{ config, pkgs, ... }:

{
  # Laptop-specific configuration
  
  # Hostname
  networking.hostName = "nixos-laptop";

  # Hardware configuration (placeholder - should be generated by nixos-generate-config)
  imports = [
    ./hardware-configuration.nix
  ];

  # Enable X11 windowing system
  services.xserver = {
    enable = true;
    
    # Enable KDE Plasma Desktop Environment
    displayManager.sddm.enable = true;
    desktopManager.plasma5.enable = true;
    
    # Keyboard layout
    xkb.layout = "us";
    
    # Enable touchpad support
    libinput.enable = true;
  };

  # Laptop-specific packages
  environment.systemPackages = with pkgs; [
    # Desktop applications
    firefox
    vscode
    
    # System monitoring
    powertop
    acpi
    
    # Battery management
    tlp
  ];

  # Power management for laptops
  services.tlp = {
    enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
      
      CPU_ENERGY_PERF_POLICY_ON_AC = "performance";
      CPU_ENERGY_PERF_POLICY_ON_BAT = "power";
      
      START_CHARGE_THRESH_BAT0 = 75;
      STOP_CHARGE_THRESH_BAT0 = 80;
    };
  };

  # Enable thermald for Intel CPUs
  services.thermald.enable = true;

  # Backlight control
  programs.light.enable = true;

  # Enable CUPS for printing
  services.printing.enable = true;

  # Define a user account
  users.users.user = {
    isNormalUser = true;
    description = "Laptop User";
    extraGroups = [ "networkmanager" "wheel" "video" ];
    # Set password with: passwd user
    # Or use hashedPassword option
  };

  # Enable Bluetooth
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;
}
