{ config, lib, pkgs, modulesPath, ... }:

{
  # Hardware configuration for laptop
  # This file should be generated by nixos-generate-config
  # Below is a template - replace with your actual hardware configuration
  
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Boot configuration
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; # Use "kvm-amd" for AMD processors
  boot.extraModulePackages = [ ];

  # Filesystems - TEMPLATE ONLY, replace with your actual configuration
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  # Swap - uncomment and configure if needed
  # swapDevices = [
  #   { device = "/dev/disk/by-label/swap"; }
  # ];

  # CPU microcode updates
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # For AMD: hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Graphics
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };

  # Networking
  networking.useDHCP = lib.mkDefault true;

  # Laptop-specific power management
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
