{ config, pkgs, ... }:

{
  # Desktop-specific configuration
  
  # Hostname
  networking.hostName = "nixos-desktop";

  # Hardware configuration (placeholder - should be generated by nixos-generate-config)
  imports = [
    ./hardware-configuration.nix
  ];

  # Enable X11 windowing system
  services.xserver = {
    enable = true;
    
    # Enable GNOME Desktop Environment
    displayManager.gdm.enable = true;
    desktopManager.gnome.enable = true;
    
    # Keyboard layout
    xkb.layout = "us";
  };

  # Desktop-specific packages
  environment.systemPackages = with pkgs; [
    # Desktop applications
    firefox
    chromium
    vscode
    libreoffice
    
    # Graphics
    gimp
    inkscape
    
    # Media
    vlc
    
    # Communication
    discord
    slack
  ];

  # Enable CUPS for printing
  services.printing.enable = true;

  # Enable touchpad support (can be enabled/disabled)
  # services.xserver.libinput.enable = true;

  # Define a user account
  users.users.user = {
    isNormalUser = true;
    description = "Desktop User";
    extraGroups = [ "networkmanager" "wheel" "docker" ];
    # Set password with: passwd user
    # Or use hashedPassword option
  };

  # Enable Docker
  virtualisation.docker.enable = true;

  # Graphics drivers (uncomment as needed)
  # hardware.opengl.enable = true;
  # services.xserver.videoDrivers = [ "nvidia" ]; # For NVIDIA
  # services.xserver.videoDrivers = [ "amdgpu" ]; # For AMD
}
